from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from app.database import get_db
from app.schemas.recommendation import RecommendationResponse
from app.services.recommendation_service import RecommendationService
from app.services.advice_service import AdviceService
from app.core.dependencies import get_current_user_id, get_matcher
from app.ai.semantic_matcher import SemanticMatcher

router = APIRouter()


@router.get("", response_model=list[RecommendationResponse])
def get_recommendations(
    user_id: str = Depends(get_current_user_id),
    db: Session = Depends(get_db),
):
    """Return the current user's stored AI-ranked job recommendations."""
    return RecommendationService(db).get_recommendations(user_id)


@router.post("/generate", response_model=list[RecommendationResponse])
def generate_recommendations(
    user_id: str = Depends(get_current_user_id),
    db: Session = Depends(get_db),
    matcher: SemanticMatcher = Depends(get_matcher),
):
    """
    Trigger the AI matching engine.
    Scores all active jobs against the user's skills using:
      final = skill×0.60 + title×0.25 + experience×0.15
    """
    return RecommendationService(db, matcher).generate(user_id)


@router.get("/advice")
def get_advice(
    force: bool = Query(False, description="Force regeneration ignoring the 24h cache"),
    user_id: str = Depends(get_current_user_id),
    db: Session = Depends(get_db),
):
    """
    Return a personalised career roadmap for the current user.

    - Cached for 24 hours per user (free Groq tier friendly).
    - Generated by Groq llama3-8b-8192 using profile + missing skills from recs.
    - Falls back to a structured template when the API key is absent.
    - Pass ?force=true to bypass the cache and regenerate immediately.

    Returns: { "content": str, "generated_at": str, "cached": bool }
    """
    return AdviceService(db).get_or_generate(user_id, force=force)
