"""phase3_add_semantic_scores_to_recommendations

Revision ID: 2a6ab5e3ef6b
Revises: d9e2c14661b1
Create Date: 2026-05-29 21:08:08.421929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6ab5e3ef6b'
down_revision: Union[str, None] = 'd9e2c14661b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add as nullable first, backfill existing rows, then enforce NOT NULL
    op.add_column('recommendations', sa.Column('semantic_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('keyword_score',  sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('explanation',    sa.JSON(),  nullable=True))
    # Existing recommendations get 0.0 for the new score fields
    op.execute("UPDATE recommendations SET semantic_score = 0.0, keyword_score = 0.0 WHERE semantic_score IS NULL")
    # Now safe to enforce NOT NULL
    op.alter_column('recommendations', 'semantic_score', nullable=False)
    op.alter_column('recommendations', 'keyword_score',  nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'explanation')
    op.drop_column('recommendations', 'keyword_score')
    op.drop_column('recommendations', 'semantic_score')
    # ### end Alembic commands ###
