"""add_title_experience_scores_to_recommendations

Revision ID: 2d69b259296d
Revises: c5825ba6d749
Create Date: 2026-06-04 01:45:49.114061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d69b259296d'
down_revision: Union[str, None] = 'c5825ba6d749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('skill_score', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    op.add_column('recommendations', sa.Column('title_score', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    op.add_column('recommendations', sa.Column('experience_score', sa.Float(), server_default=sa.text('0.5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'experience_score')
    op.drop_column('recommendations', 'title_score')
    op.drop_column('recommendations', 'skill_score')
    # ### end Alembic commands ###
