"""add diploma_score

Revision ID: 55ccccd7b1e8
Revises: 67c2226e7d67
Create Date: 2026-06-10 22:28:48.718326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ccccd7b1e8'
down_revision: Union[str, None] = '67c2226e7d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('diploma_score', sa.Float(), server_default=sa.text('0.7'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'diploma_score')
    # ### end Alembic commands ###
