"""add score_history

Revision ID: 5b8e2894cc5e
Revises: a1b2c3d4e5f6
Create Date: 2026-06-08 15:24:49.942483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8e2894cc5e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=False),
    sa.Column('total_matched', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_history_recorded_at'), 'score_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_score_history_user_id'), 'score_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_history_user_id'), table_name='score_history')
    op.drop_index(op.f('ix_score_history_recorded_at'), table_name='score_history')
    op.drop_table('score_history')
    # ### end Alembic commands ###
