"""add required_diploma_experience_to_jobs

Revision ID: c5825ba6d749
Revises: 679e25d92300
Create Date: 2026-06-04 01:35:30.287293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5825ba6d749'
down_revision: Union[str, None] = '679e25d92300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_diploma', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('required_experience', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'required_experience')
    op.drop_column('jobs', 'required_diploma')
    # ### end Alembic commands ###
