"""phase1_add_fingerprint_expires_at_role

Revision ID: d9e2c14661b1
Revises: ce4c5905a1c7
Create Date: 2026-05-26 13:58:22.347592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9e2c14661b1'
down_revision: Union[str, None] = 'ce4c5905a1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('jobs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_job_expires_active', 'jobs', ['expires_at', 'is_active'], unique=False)
    op.create_index('idx_job_source_active', 'jobs', ['source_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_jobs_source_name'), 'jobs', ['source_name'], unique=False)
    op.create_unique_constraint(None, 'jobs', ['fingerprint'])
    # Create the PostgreSQL ENUM type explicitly (must exist before column references it)
    user_role_enum_type = sa.Enum('student', 'recruiter', 'admin', name='user_role_enum')
    user_role_enum_type.create(op.get_bind(), checkfirst=True)
    # Add role as nullable first, fill existing rows, then make it NOT NULL
    op.add_column('users', sa.Column('role',
        sa.Enum('student', 'recruiter', 'admin', name='user_role_enum', create_type=False),
        nullable=True))
    op.execute("UPDATE users SET role = 'student' WHERE role IS NULL")
    op.alter_column('users', 'role', nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'role')
    sa.Enum(name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_source_name'), table_name='jobs')
    op.drop_index('idx_job_source_active', table_name='jobs')
    op.drop_index('idx_job_expires_active', table_name='jobs')
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'expires_at')
    op.drop_column('jobs', 'fingerprint')
    op.drop_column('jobs', 'scraped_at')
    # ### end Alembic commands ###
